version: "3.4"
services:
    mysql:
        build:
            context: ./crm-mysql
            dockerfile: Dockerfile
        image: "crm-mysql:latest"
        ports:
            - 3306:3306
        volumes:
            - /opt/docker-volumes/project_start/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root